CONFIGURATION := gcc-release-64
CXX := g++

CXXFLAGS := -O3 \
            -Wall \
            -std=c++17 \
            -m64 \
            -Wno-sign-compare \
            -Wno-switch \
            -isystem ../overrides/gcc \
            -ffloat-store \
            -fwrapv \
            -g0 \
            -DNDEBUG

include common.mk
