CONFIGURATION := gcc-debug-32
CXX := g++

CXXFLAGS := -Wall \
            -std=c++17 \
            -m32 \
            -Wno-sign-compare \
            -Wno-switch \
            -isystem ../overrides/gcc \
            -ffloat-store \
            -fwrapv \
            -g3

include common.mk
