CONFIGURATION := clang-release-64
CXX := clang

CXXFLAGS := -O3 \
            -Wall \
            -std=c++17 \
            -m64 \
            -stdlib=libc++ \
            -isystem ../overrides/clang \
            -fwrapv \
            -g0 \
            -DNDEBUG

include common.mk
