CONFIGURATION := clang-release-32
CXX := clang

CXXFLAGS := -O3 \
            -Wall \
            -std=c++17 \
            -m32 \
            -stdlib=libc++ \
            -Wno-unqualified-std-cast-call \
            -isystem ../overrides/clang \
            -fwrapv \
            -g0 \
            -DNDEBUG

include common.mk
