CONFIGURATION := clang-debug-32
CXX := clang

CXXFLAGS := -Wall \
            -std=c++17 \
            -m32 \
            -stdlib=libc++ \
            -isystem ../overrides/clang \
            -fwrapv \
            -g3

include common.mk
